version: 2
jobs:
  "RxStarscream Tests":
    working_directory: ~/RxSwiftCommunity/RxStarscream
    parallelism: 1
    shell: /bin/bash --login
    environment:
      XCODE_TEST_REPORTS: /tmp/xcode-test-results
      LANG: en_US.UTF-8
    macos:
      xcode: '10.2.0'
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS $XCODE_TEST_REPORTS
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
            - v1-dep-master-
            - v1-dep-
      - run:
          name: Bootstrap Carthage
          command: scripts/bootstrap.sh
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - Carthage
      - run:
          name: iOS, Swift 5
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=5.0 -scheme RxStarscream -project RxStarscream.xcodeproj -sdk iphonesimulator -destination "name=iPhone 8" |  xcpretty -c -r html --output $XCODE_TEST_REPORTS/iOS_swift5.html
      - run:
          name: macOS, Swift 5
          command: set -o pipefail && xcodebuild test SWIFT_VERSION=5.0 -scheme RxStarscream-macOS -project RxStarscream.xcodeproj -sdk macosx | xcpretty -c -r html --output $XCODE_TEST_REPORTS/macOS_swift5.html
      - store_artifacts:
          path: $XCODE_TEST_REPORTS
  "RxStarscream Release":
    working_directory: ~/RxSwiftCommunity/RxStarscream
    parallelism: 1
    shell: /bin/bash --login
    environment:
      LANG: en_US.UTF-8
    macos:
      xcode: '10.2.0'
    steps:
      - checkout
      - run:
          name: Setup CocoaPods
          command: pod setup
      - run:
          name: Override Circle CI Config
          command: rm ~/.cocoapods/config.yaml # This hack is needed since CircleCI forces --verbose
      - run:
          name: Push Podspec to Trunk
          command: pod trunk push --skip-tests --allow-warnings --swift-version=5.0
workflows:
  version: 2
  build:
    jobs:
      - "RxStarscream Tests":
          filters:
            tags:
              ignore: /[0-9]+(\.[0-9]+)*/
  release:
    jobs:
      - "RxStarscream Release":
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*/
